---
title: "Phylo"
author: "Heru Handika"
date: "10/15/2021"
output: html_document
---

```{r}
pacman::p_load(here)
pacman::p_load(ape)
pacman::p_load(tidyr)
pacman::p_load(dplyr)
pacman::p_load(readr)
pacman::p_load(ggtree)
pacman::p_load(tidytree)
pacman::p_load(ggplot2)
```

## Data loading and distance matrix computing 

```{r}
alignment.path <- here::here("data", "alignments", "1_cytb_dist.phy")

alignment <- ape::read.dna(alignment.path, format="interleaved")

distance <- alignment |> 
  ape::dist.dna(model = "JC69", variance = FALSE, gamma = FALSE, pairwise.deletion = FALSE, base.freq = NULL, as.matrix = TRUE) |>
  # Ape save to matrix. We convert it to tibble data frame
  # for easy manipulation using tidyverse syntax
  tibble::as_tibble(rownames = "Taxon")

distance.long <- distance |>
  tidyr::pivot_longer(!Taxon, names_to = "Taxon2", values_to = "JC69") 

frateromys.long <- distance.long |>
  dplyr::filter(stringr::str_starts(Taxon, "Frateromys")) |>
  dplyr::filter(stringr::str_starts(Taxon2, "Frateromys")) |> 
  # Remove the same individual from rows
  dplyr::filter(Taxon != Taxon2)
  
frateromys <- frateromys.long |> 
  # Ignore inter-species relationship. We detect based on naming patterns.
  # dplyr::filter(stringr::str_extract(Taxon, "^[^_]+_[^_]+") == stringr::str_extract(Taxon2, "^[^_]+_[^_]+")) |> 
  tidyr::pivot_wider(id_cols = Taxon, names_from = Taxon2, values_from = JC69) |> 
  dplyr::relocate(Frateromys_fratrorum_KCR4049_Bogani, .after = Taxon)

# Remove duplicate values in the upper triangle of the matrix
frateromys[upper.tri(frateromys)] <- NA
```

# Save intra-specific genetic distance (OPTIONAL)

```{r}
readr::write_csv(frateromys, here::here("results", "intra-frateromys-distanceJC69.csv"), na="")
```

## Intra-distance histogram

```{r}
species_data <- all_species |> 
  dplyr::mutate(mode = "inter-specific") |> 
  dplyr::rename(Taxon = Species) |> 
  dplyr::rename(Taxon2 = Species2)

frateromys_data <- frateromys.long |> 
  dplyr::mutate(mode = "intra-frateromys") |> 
  dplyr::rename(Distance = JC69) |> 
  # Ignore inter-species relationship. We detect based on naming patterns.
  dplyr::filter(stringr::str_extract(Taxon, "^[^_]+_[^_]+") == stringr::str_extract(Taxon2, "^[^_]+_[^_]+")) 

df <- rbind(species_data, frateromys_data)

ggplot(df, aes(x = Distance, color = mode)) + 
  geom_histogram() +
  scale_color_brewer(palette="Dark2")
  theme_classic()
```

## Computing avarage genetic distance for inter-specific relationship

```{r}
distance.inter <- distance.long |>
  tidyr::separate(Taxon, c("Genus1", "Species1", "Museum_no"), sep="_", extra = "drop") |>
  tidyr::separate(Taxon2, c("Genus2", "Species2", "Museum_no2"), sep="_", extra = "drop") |>
  tidyr::unite("Species", Genus1, Species1) |>
  tidyr::unite("Species2", Genus2, Species2)

all_species <- distance.inter |>
  dplyr::group_by(Species, Species2) |>
  dplyr::summarise(Distance = mean(JC69)) |>
  dplyr::filter(Species != Species2)

inter_dist_matrix <- all_species |> # Include only inter-specific relationship
  tidyr::pivot_wider(id_cols = Species, names_from = Species2, values_from = Distance) |>
  # Somehow tidyr messes up the order of the columns. 
  # B. andrewsi comes last. Here, we move it into the second column
  dplyr::relocate(Bunomys_andrewsi, .after = Species)

# Remove duplicate values in the upper triangle of the matrix
inter_dist_matrix[upper.tri(inter_dist_matrix)] <- NA

readr::write_csv(inter_dist_matrix, here("results", "inter-specific-dist-matrix.csv"), na="")
```
